# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xepmts
from api.account_api import AccountApi  # noqa: E501
from xepmts.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = api.account_api.AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_account_item(self):
        """Test case for delete_account_item

        Deletes a Account document  # noqa: E501
        """
        pass

    def test_get_account_item(self):
        """Test case for get_account_item

        Retrieves a Account document  # noqa: E501
        """
        pass

    def test_get_account_item_by_username(self):
        """Test case for get_account_item_by_username

        Retrieves a Account document by username  # noqa: E501
        """
        pass

    def test_get_accounts(self):
        """Test case for get_accounts

        Retrieves one or more Accounts  # noqa: E501
        """
        pass

    def test_post_accounts(self):
        """Test case for post_accounts

        Stores one or more Accounts.  # noqa: E501
        """
        pass

    def test_put_account_item(self):
        """Test case for put_account_item

        Replaces a Account document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
