# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xepmts
from api.pmt_api import PmtApi  # noqa: E501
from xepmts.rest import ApiException


class TestPmtApi(unittest.TestCase):
    """PmtApi unit test stubs"""

    def setUp(self):
        self.api = api.pmt_api.PmtApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_pmt_item(self):
        """Test case for delete_pmt_item

        Deletes a Pmt document  # noqa: E501
        """
        pass

    def test_delete_pmts(self):
        """Test case for delete_pmts

        Deletes all Pmts  # noqa: E501
        """
        pass

    def test_get_pmt_item(self):
        """Test case for get_pmt_item

        Retrieves a Pmt document  # noqa: E501
        """
        pass

    def test_get_pmt_item_by_serial_number(self):
        """Test case for get_pmt_item_by_serial_number

        Retrieves a Pmt document by serial_number  # noqa: E501
        """
        pass

    def test_get_pmts(self):
        """Test case for get_pmts

        Retrieves one or more Pmts  # noqa: E501
        """
        pass

    def test_post_pmts(self):
        """Test case for post_pmts

        Stores one or more Pmts.  # noqa: E501
        """
        pass

    def test_put_pmt_item(self):
        """Test case for put_pmt_item

        Replaces a Pmt document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
