# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    The version of the OpenAPI document: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import xepmts
from xepmts.api.voltage_map_name_api import VoltageMapNameApi  # noqa: E501
from xepmts.rest import ApiException


class TestVoltageMapNameApi(unittest.TestCase):
    """VoltageMapNameApi unit test stubs"""

    def setUp(self):
        self.api = xepmts.api.voltage_map_name_api.VoltageMapNameApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_voltage_map_name_item(self):
        """Test case for get_voltage_map_name_item

        Retrieves a VoltageMapName document  # noqa: E501
        """
        pass

    def test_get_voltage_maps_names(self):
        """Test case for get_voltage_maps_names

        Retrieves one or more VoltageMaps/names  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
