# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xepmts
from models.voltage_change import VoltageChange  # noqa: E501
from xepmts.rest import ApiException


class TestVoltageChange(unittest.TestCase):
    """VoltageChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVoltageChange(self):
        """Test VoltageChange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xepmts.models.voltage_change.VoltageChange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
