# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xepmts
from models.install import Install  # noqa: E501
from xepmts.rest import ApiException


class TestInstall(unittest.TestCase):
    """Install unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstall(self):
        """Test Install"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xepmts.models.install.Install()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
