# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xepmts
from api.install_api import InstallApi  # noqa: E501
from xepmts.rest import ApiException


class TestInstallApi(unittest.TestCase):
    """InstallApi unit test stubs"""

    def setUp(self):
        self.api = api.install_api.InstallApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_install_item(self):
        """Test case for delete_install_item

        Deletes a Install document  # noqa: E501
        """
        pass

    def test_delete_installs(self):
        """Test case for delete_installs

        Deletes all Installs  # noqa: E501
        """
        pass

    def test_get_install_item(self):
        """Test case for get_install_item

        Retrieves a Install document  # noqa: E501
        """
        pass

    def test_get_install_item_by_uid(self):
        """Test case for get_install_item_by_uid

        Retrieves a Install document by uid  # noqa: E501
        """
        pass

    def test_get_installs(self):
        """Test case for get_installs

        Retrieves one or more Installs  # noqa: E501
        """
        pass

    def test_post_installs(self):
        """Test case for post_installs

        Stores one or more Installs.  # noqa: E501
        """
        pass

    def test_put_install_item(self):
        """Test case for put_install_item

        Replaces a Install document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
