# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xepmts
from api.gain_api import GainApi  # noqa: E501
from xepmts.rest import ApiException


class TestGainApi(unittest.TestCase):
    """GainApi unit test stubs"""

    def setUp(self):
        self.api = api.gain_api.GainApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_gain_item(self):
        """Test case for delete_gain_item

        Deletes a Gain document  # noqa: E501
        """
        pass

    def test_delete_gains(self):
        """Test case for delete_gains

        Deletes all Gains  # noqa: E501
        """
        pass

    def test_get_gain_item(self):
        """Test case for get_gain_item

        Retrieves a Gain document  # noqa: E501
        """
        pass

    def test_get_gains(self):
        """Test case for get_gains

        Retrieves one or more Gains  # noqa: E501
        """
        pass

    def test_post_gains(self):
        """Test case for post_gains

        Stores one or more Gains.  # noqa: E501
        """
        pass

    def test_put_gain_item(self):
        """Test case for put_gain_item

        Replaces a Gain document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
