# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xepmts
from api.afterpulse_api import AfterpulseApi  # noqa: E501
from xepmts.rest import ApiException


class TestAfterpulseApi(unittest.TestCase):
    """AfterpulseApi unit test stubs"""

    def setUp(self):
        self.api = api.afterpulse_api.AfterpulseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_afterpulse_item(self):
        """Test case for delete_afterpulse_item

        Deletes a Afterpulse document  # noqa: E501
        """
        pass

    def test_delete_afterpulses(self):
        """Test case for delete_afterpulses

        Deletes all Afterpulses  # noqa: E501
        """
        pass

    def test_get_afterpulse_item(self):
        """Test case for get_afterpulse_item

        Retrieves a Afterpulse document  # noqa: E501
        """
        pass

    def test_get_afterpulses(self):
        """Test case for get_afterpulses

        Retrieves one or more Afterpulses  # noqa: E501
        """
        pass

    def test_post_afterpulses(self):
        """Test case for post_afterpulses

        Stores one or more Afterpulses.  # noqa: E501
        """
        pass

    def test_put_afterpulse_item(self):
        """Test case for put_afterpulse_item

        Replaces a Afterpulse document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
