# coding: utf-8

"""
    PMT API

    API for the XenonnT PMT database  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: joe.mosbacher@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class VoltageMapVoltages(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'voltage': 'float',
        'pmt_index': 'int'
    }

    attribute_map = {
        'voltage': 'voltage',
        'pmt_index': 'pmt_index'
    }

    def __init__(self, voltage=None, pmt_index=None):  # noqa: E501
        """VoltageMapVoltages - a model defined in Swagger"""  # noqa: E501
        self._voltage = None
        self._pmt_index = None
        self.discriminator = None
        if voltage is not None:
            self.voltage = voltage
        if pmt_index is not None:
            self.pmt_index = pmt_index

    @property
    def voltage(self):
        """Gets the voltage of this VoltageMapVoltages.  # noqa: E501


        :return: The voltage of this VoltageMapVoltages.  # noqa: E501
        :rtype: float
        """
        return self._voltage

    @voltage.setter
    def voltage(self, voltage):
        """Sets the voltage of this VoltageMapVoltages.


        :param voltage: The voltage of this VoltageMapVoltages.  # noqa: E501
        :type: float
        """

        self._voltage = voltage

    @property
    def pmt_index(self):
        """Gets the pmt_index of this VoltageMapVoltages.  # noqa: E501


        :return: The pmt_index of this VoltageMapVoltages.  # noqa: E501
        :rtype: int
        """
        return self._pmt_index

    @pmt_index.setter
    def pmt_index(self, pmt_index):
        """Sets the pmt_index of this VoltageMapVoltages.


        :param pmt_index: The pmt_index of this VoltageMapVoltages.  # noqa: E501
        :type: int
        """

        self._pmt_index = pmt_index

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VoltageMapVoltages, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VoltageMapVoltages):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
